name: 'Update-Branch-Protection'
description: 'Custom GitHub action based on Node.js to automatically apply branch protection rules on a repository.'
author: 'Eric Chapman'

inputs:
  token:
    description: 'This should have Admin privileges or should be an Org Level Owner'
    required: true
  organisationName:
    description: 'The name of your GitHub organization the repository belongs to'
    required: true
  repositoryName:
    description: 'The name of the repository this request will run against'
    required: true
  branchName:
    description: 'The name of the branch to apply the rules to'
    required: false
    default: 'main'
  rulesPath:
    description: 'The path of the rules json file for branch protection'
    default: './rules.json'
    required: true
  action:
    description: 'Set or Add or Delete Branch protection. Default is set.'
    default: 'set'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
  
branding:
  icon: 'activity'
  color: 'blue'
